PackageIdentifier: Aleckstygit.WayCoder
PackageVersion: 0.96.559
InstallerLocale: zh-CN
InstallerType: portable
Commands:
  - waycoder
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alecksty/waycoder/releases/download/v0.96.559/waycoder-v0.96.559-win-x64.zip
    InstallerSha256: d7f639d279d1d413c349971df4a8428400fca3808bde03321ef6847ebe36b200
  - Architecture: arm64
    InstallerUrl: https://github.com/alecksty/waycoder/releases/download/v0.96.559/waycoder-v0.96.559-win-arm64.zip
    InstallerSha256: 22652364f023ec70ad9d5b1fd7e3e9a116590a27f720ada7fe34dcb8457662b3
ManifestType: installer
ManifestVersion: 1.6.0
