PackageIdentifier: Aleckstygit.Dolaima
PackageVersion: 0.96.810
InstallerLocale: zh-CN
InstallerType: portable
Commands:
  - waycoder
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alecksty/waycoder/releases/download/v0.96.810/waycoder-v0.96.810-win-x64.zip
    InstallerSha256: 4812924706a4332ee4ea04782fd8ed68540aacabcbcf2899885f4cc45d36a109
  - Architecture: arm64
    InstallerUrl: https://github.com/alecksty/waycoder/releases/download/v0.96.810/waycoder-v0.96.810-win-arm64.zip
    InstallerSha256: 37c6f3dd356a7c6ba5c716298cf6face89262cb5c6e709989332dc3c48c1ad95
ManifestType: installer
ManifestVersion: 1.6.0
